# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Thu Feb 20 15:44:31 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(921, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setBaseSize(QtCore.QSize(350, 350))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 903, 324))
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.armylist = QtGui.QTreeWidget(self.page)
        self.armylist.setAnimated(True)
        self.armylist.setWordWrap(True)
        self.armylist.setObjectName(_fromUtf8("armylist"))
        self.armylist.headerItem().setText(0, _fromUtf8("Name"))
        font = QtGui.QFont()
        font.setKerning(False)
        self.armylist.headerItem().setFont(0, font)
        self.armylist.header().setCascadingSectionResizes(True)
        self.armylist.header().setHighlightSections(True)
        self.armylist.header().setSortIndicatorShown(True)
        self.horizontalLayout_2.addWidget(self.armylist)
        self.armyopts = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.armyopts.sizePolicy().hasHeightForWidth())
        self.armyopts.setSizePolicy(sizePolicy)
        self.armyopts.setMinimumSize(QtCore.QSize(150, 0))
        self.armyopts.setMaximumSize(QtCore.QSize(150, 16777215))
        self.armyopts.setSizeIncrement(QtCore.QSize(150, 0))
        self.armyopts.setBaseSize(QtCore.QSize(150, 0))
        self.armyopts.setAutoFillBackground(False)
        self.armyopts.setFrameShape(QtGui.QFrame.Box)
        self.armyopts.setFrameShadow(QtGui.QFrame.Plain)
        self.armyopts.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.armyopts.setWordWrap(True)
        self.armyopts.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.armyopts.setObjectName(_fromUtf8("armyopts"))
        self.horizontalLayout_2.addWidget(self.armyopts)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 903, 324))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.squadtable = QtGui.QTableWidget(self.page_2)
        self.squadtable.setObjectName(_fromUtf8("squadtable"))
        self.squadtable.setColumnCount(7)
        self.squadtable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.squadtable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.squadtable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.squadtable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.squadtable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.squadtable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.squadtable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.squadtable.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_4.addWidget(self.squadtable)
        self.squadopts = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.squadopts.sizePolicy().hasHeightForWidth())
        self.squadopts.setSizePolicy(sizePolicy)
        self.squadopts.setMinimumSize(QtCore.QSize(150, 0))
        self.squadopts.setMaximumSize(QtCore.QSize(150, 16777215))
        self.squadopts.setBaseSize(QtCore.QSize(150, 0))
        self.squadopts.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.squadopts.setObjectName(_fromUtf8("squadopts"))
        self.horizontalLayout_4.addWidget(self.squadopts)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 903, 324))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.modstable = QtGui.QTableWidget(self.page_4)
        self.modstable.setObjectName(_fromUtf8("modstable"))
        self.modstable.setColumnCount(7)
        self.modstable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.modstable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.modstable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.modstable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.modstable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.modstable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.modstable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.modstable.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.modstable)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 903, 324))
        self.page_3.setAccessibleName(_fromUtf8(""))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.templatetable = QtGui.QTableWidget(self.page_3)
        self.templatetable.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.templatetable.setObjectName(_fromUtf8("templatetable"))
        self.templatetable.setColumnCount(10)
        self.templatetable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.templatetable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.templatetable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.templatetable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.templatetable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.templatetable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.templatetable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.templatetable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.templatetable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.templatetable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.templatetable.setHorizontalHeaderItem(9, item)
        self.templatetable.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.templatetable)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page_5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.typetable = QtGui.QTableWidget(self.page_5)
        self.typetable.setObjectName(_fromUtf8("typetable"))
        self.typetable.setColumnCount(2)
        self.typetable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.typetable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.typetable.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_3.addWidget(self.typetable)
        self.mobilitytable = QtGui.QTableWidget(self.page_5)
        self.mobilitytable.setObjectName(_fromUtf8("mobilitytable"))
        self.mobilitytable.setColumnCount(2)
        self.mobilitytable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mobilitytable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mobilitytable.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_3.addWidget(self.mobilitytable)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.addaction = QtGui.QAction(MainWindow)
        self.addaction.setObjectName(_fromUtf8("addaction"))
        self.removeaction = QtGui.QAction(MainWindow)
        self.removeaction.setObjectName(_fromUtf8("removeaction"))
        self.updateaction = QtGui.QAction(MainWindow)
        self.updateaction.setObjectName(_fromUtf8("updateaction"))
        self.toolBar.addAction(self.addaction)
        self.toolBar.addAction(self.removeaction)
        self.toolBar.addAction(self.updateaction)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ArmyBuilder", None))
        self.armylist.headerItem().setText(1, _translate("MainWindow", "TS", None))
        self.armylist.headerItem().setText(2, _translate("MainWindow", "Raise", None))
        self.armylist.headerItem().setText(3, _translate("MainWindow", "Supply", None))
        self.armylist.headerItem().setText(4, _translate("MainWindow", "Weight", None))
        self.armylist.headerItem().setText(5, _translate("MainWindow", "TL", None))
        self.armylist.headerItem().setText(6, _translate("MainWindow", "Type", None))
        self.armylist.headerItem().setText(7, _translate("MainWindow", "Mods", None))
        self.armylist.headerItem().setText(8, _translate("MainWindow", "Casualities", None))
        self.armyopts.setText(_translate("MainWindow", "Свойства Армий", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Армии", None))
        item = self.squadtable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.squadtable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.squadtable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.squadtable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Mods", None))
        item = self.squadtable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Casualities", None))
        item = self.squadtable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Template", None))
        item = self.squadtable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Mobility", None))
        self.squadopts.setText(_translate("MainWindow", "TextLabel", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Отряды", None))
        item = self.modstable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.modstable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.modstable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TS", None))
        item = self.modstable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Raise", None))
        item = self.modstable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Supply", None))
        item = self.modstable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Weight", None))
        item = self.modstable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "TL", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Модификаторы", None))
        item = self.templatetable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.templatetable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.templatetable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TS", None))
        item = self.templatetable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Raise", None))
        item = self.templatetable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Supply", None))
        item = self.templatetable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Weight", None))
        item = self.templatetable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "TL", None))
        item = self.templatetable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.templatetable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Mobility", None))
        item = self.templatetable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Скорость", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Шаблоны войск", None))
        item = self.typetable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.typetable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.mobilitytable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.mobilitytable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Типы войск", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.addaction.setText(_translate("MainWindow", "+", None))
        self.addaction.setToolTip(_translate("MainWindow", "Добавить", None))
        self.removeaction.setText(_translate("MainWindow", "-", None))
        self.removeaction.setToolTip(_translate("MainWindow", "Удалить ", None))
        self.updateaction.setText(_translate("MainWindow", "Upd", None))
        self.updateaction.setToolTip(_translate("MainWindow", "Update data", None))

